name: CI
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ["12", "14", "16"]
        name: Node ${{ matrix.node }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Set up Node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}
            - name: Upgrade yarn
              run: yarn install --frozen-lockfile
            - name: Install
              run: yarn ci
            - name: Build
              run: yarn run build
            - name: Test
              run: yarn test
            - name: Lint
              run: yarn run lint
